// ============================================================
// ai.js — AI Coach (Gemini) + Program Kaydetme
// ============================================================

const aiChoices      = { ai_exp: null, ai_eq: null }
let selectedDays     = []
let savedAIProgramId = null

function toggleDay(btn) {
  const day = parseInt(btn.dataset.day)
  if (selectedDays.includes(day)) {
    selectedDays = selectedDays.filter(d => d !== day)
    btn.classList.remove('selected')
  } else {
    selectedDays.push(day)
    btn.classList.add('selected')
  }
}

async function getAISuggestion() {
  const goal             = document.getElementById('ai-goal').value
  const experience_level = aiChoices.ai_exp
  const equipment        = aiChoices.ai_eq
  const injuries         = document.getElementById('ai-injuries').value.trim()

  if (selectedDays.length === 0) { showErr('ai-error', 'Please select at least 1 training day'); return }
  if (!experience_level) { showErr('ai-error', 'Select experience level'); return }
  if (!equipment)        { showErr('ai-error', 'Select equipment'); return }

  const days_per_week = selectedDays.length
  const btn = document.getElementById('ai-generate-btn')
  btn.innerHTML = '<div class="spinner" style="width:18px;height:18px;border-width:2px;margin:0 auto"></div>'
  btn.disabled  = true
  hideErr('ai-error')
  document.getElementById('ai-result').classList.add('hidden')

  try {
    const result = await api('/ai/workout-suggestion', 'POST', {
      days_per_week, available_days: selectedDays,
      goal, experience_level, equipment,
      injuries: injuries || null
    })
    document.getElementById('ai-response-text').innerHTML =
      result.suggestion.replace(/\n/g, '<br>')
    const goalLabels = {
      muscle_gain:'Muscle Gain', fat_loss:'Fat Loss',
      weight_loss:'Weight Loss', strength:'Strength', endurance:'Endurance'
    }
    document.getElementById('ai-save-name').value = `AI ${goalLabels[goal] || goal} Program`
    document.getElementById('ai-result').classList.remove('hidden')
    document.getElementById('ai-result').scrollIntoView({ behavior: 'smooth' })
  } catch (err) {
    showErr('ai-error', err.message.includes('Profile not found')
      ? 'Please complete your profile first.' : err.message)
  } finally {
    btn.innerHTML = '<i data-lucide="sparkles"></i> Generate My Program'
    btn.disabled  = false
    lucide.createIcons()
  }
}

// AI çıktısını program olarak kaydet
async function saveAIProgram() {
  const name          = document.getElementById('ai-save-name').value.trim()
  const goal          = document.getElementById('ai-goal').value
  const days_per_week = selectedDays.length || 3
  if (!name || name.length < 3) { showToast('Program name min 3 chars', 'error'); return }

  const btn = document.getElementById('ai-save-btn')
  btn.textContent = 'Saving...'
  btn.disabled    = true
  try {
    const result = await api('/ai/workout-suggestion/save', 'POST', {
      name, days_per_week, goal, description: 'Generated by Gemini AI'
    })
    savedAIProgramId = result.program.id
    showToast('Program saved!', 'success')
    document.getElementById('ai-add-exercises').classList.remove('hidden')
    document.getElementById('ai-add-exercises').scrollIntoView({ behavior: 'smooth' })
    btn.textContent = '✅ Saved'
    btn.disabled    = true
    // Egzersiz listesi yüklü değilse yükle
    if (!allExercises.length) allExercises = await api('/exercises')
  } catch (err) {
    showToast(`Error: ${err.message}`, 'error')
    btn.textContent = 'Save Program'
    btn.disabled    = false
  }
}

// ── Egzersiz Arama Dropdown ──────────────────────────────────
// training.js'deki searchProgEx ile aynı mantık

function searchAIExercise() {
  const q    = document.getElementById('ai-ex-search').value.toLowerCase()
  const drop = document.getElementById('ai-ex-drop')

  if (!q || q.length < 2) { drop.classList.add('hidden'); return }

  const filtered = allExercises
    .filter(e => e.name.toLowerCase().includes(q) || e.muscle_group.toLowerCase().includes(q))
    .slice(0, 8)

  if (!filtered.length) {
    drop.innerHTML = '<div style="padding:12px;color:var(--text-3);font-size:0.85rem;text-align:center">No results</div>'
    drop.classList.remove('hidden')
    return
  }

  drop.innerHTML = filtered.map(e => `
    <div onclick="pickAIExercise(${e.id},'${e.name.replace(/'/g,"\\'")} (${e.muscle_group})')"
      style="display:flex;justify-content:space-between;align-items:center;
        padding:10px 14px;cursor:pointer;border-bottom:1px solid var(--border);
        transition:background 0.15s">
      <span style="font-size:0.88rem;color:var(--text)">${e.name}</span>
      <span class="badge badge-gold" style="font-size:0.65rem">${e.muscle_group}</span>
    </div>
  `).join('')

  drop.classList.remove('hidden')
}

function pickAIExercise(exId, label) {
  document.getElementById('ai-ex-id').value     = exId
  document.getElementById('ai-ex-search').value = label
  document.getElementById('ai-ex-drop').classList.add('hidden')
}

async function addExToAIProgram() {
  if (!savedAIProgramId) { showToast('Please save the program first', 'error'); return }

  const exId = document.getElementById('ai-ex-id').value
  const day  = parseInt(document.getElementById('ai-ex-day').value)
  const sets = parseInt(document.getElementById('ai-ex-sets').value)
  const reps = parseInt(document.getElementById('ai-ex-reps').value)

  if (!exId) { showErr('ai-ex-error', 'Please select an exercise'); return }
  if (!reps || reps < 1) { showErr('ai-ex-error', 'Please enter reps'); return }

  try {
    await api(`/programs/${savedAIProgramId}/exercises`, 'POST', {
      exercise_id: parseInt(exId), day_of_week: day, sets, target_reps: reps
    })

    const ex       = allExercises.find(e => e.id === parseInt(exId))
    const dayNames = { 1:'Mon',2:'Tue',3:'Wed',4:'Thu',5:'Fri',6:'Sat',7:'Sun' }
    const list     = document.getElementById('ai-added-list')
    const item     = document.createElement('div')
    item.className = 'day-ex-item'
    item.style.marginBottom = '6px'
    item.innerHTML = `
      <div>
        <strong style="font-size:0.85rem">${ex?.name || 'Exercise'}</strong>
        <span style="color:var(--text-3);font-size:0.78rem;margin-left:6px">
          ${dayNames[day]} · ${sets}×${reps}
        </span>
      </div>
      <span class="badge badge-green">Added ✓</span>
    `
    list.appendChild(item)

    // Formu temizle
    document.getElementById('ai-ex-search').value = ''
    document.getElementById('ai-ex-id').value     = ''
    document.getElementById('ai-ex-reps').value   = ''
    hideErr('ai-ex-error')
    showToast(`${ex?.name} added!`, 'success')
  } catch (err) { showErr('ai-ex-error', err.message) }
}

function goToAIProgram() {
  savedAIProgramId = null
  showView('training')
}